---
- name: Play roles as user
  hosts: all
  connection: local
  roles:
    - markosamuli.linuxbrew
    - Comcast.sdkman

- name: Play roles as root
  hosts: all
  connection: local
  become: true
  roles:
    - install_ssh_authorized_keys
    - common_install_packages
    - dev-sec.ssh-hardening
    - chsh_fish
    - add_to_groups
    - setup_google_drive
    - baztian.jetbrains_toolbox
    - geerlingguy.docker
    - install_tailscale
