---
- dev-sec.ssh-hardening
- telusdigital.fish
- pixelart.chrome
- pddg.xkeysnail
- markosamuli.linuxbrew
- baztian.jetbrains_toolbox
- geerlingguy.docker
- avnes.ansible-role-slack
- Comcast.sdkman
