---
- name: find the location of fish shell
  command: which fish
  register: which_fish
  ignore_errors: yes
  changed_when: no
- name: chsh fish
  user:
    name: "{{ ansible_user }}"
    shell: '{{ which_fish.stdout }}'
  when: which_fish is success
